# Generated by Django 5.2.3 on 2025-07-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto')], default='Nuevo', max_length=20)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=20)),
                ('fecha', models.DateTimeField()),
                ('responsable', models.CharField(max_length=100)),
                ('fechaResolucion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
