FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration=production
WORKDIR /app/dist/infratech-s.a
RUN npm install -g http-server
EXPOSE 8080
CMD ["http-server", "-p", "8080"]
